# calculating return values and periods using climextremes

In [1]:
import requests 
import numpy as np
import pandas as pd
import xarray as xr
from datetime import datetime

import climextremes as climext

import matplotlib.pyplot as plt
%matplotlib inline

## extracting time series from netcdf file

In [2]:
ds = xr.open_dataset("./data/pr_Amon_NorESM1-M_historical_r1i1p1_185001-200512.nc")
print(ds)

<xarray.Dataset>
Dimensions:    (time: 1872, bnds: 2, lat: 96, lon: 144)
Coordinates:
  * time       (time) object 1850-01-16 12:00:00 ... 2005-12-16 12:00:00
  * lat        (lat) float64 -90.0 -88.11 -86.21 -84.32 ... 86.21 88.11 90.0
  * lon        (lon) float64 0.0 2.5 5.0 7.5 10.0 ... 350.0 352.5 355.0 357.5
Dimensions without coordinates: bnds
Data variables:
    time_bnds  (time, bnds) object ...
    lat_bnds   (lat, bnds) float64 ...
    lon_bnds   (lon, bnds) float64 ...
    pr         (time, lat, lon) float32 ...
Attributes: (12/26)
    institution:            Norwegian Climate Centre
    institute_id:           NCC
    experiment_id:          historical
    source:                 NorESM1-M 2011  atmosphere: CAM-Oslo (CAM4-Oslo-n...
    model_id:               NorESM1-M
    forcing:                GHG, SA, Oz, Sl, Vl, BC, OC
    ...                     ...
    table_id:               Table Amon (27 April 2011) a5a1c518f52ae340313ba0...
    title:                  NorESM1-M model output prepared for CMIP5 historical
    parent_experiment:      pre-industrial control
    modeling_realm:         atmos
    realization:            1
    cmor_version:           2.6.0

In [3]:
# converting precipitation to m/day units

ds["pr"].data = ds["pr"].data * 86.4
ds["pr"].attrs["units"] = 'm/day'

In [4]:
# getting dataset specifically for defined location
# coordinates for berkeley, california

lat = 37.87
lon = 122.27
ds_berk = ds.sel(lon=lon, lat=lat, method='nearest')

In [5]:
# converting to timeseries dataframe

sr = ds_berk['pr'].to_pandas()
sr.index = sr.index.to_datetimeindex()
df = pd.DataFrame({'time':sr.index, 'pr':sr.values})

/var/folders/bz/l7frggbx71n9k19wxh7hvwsm0000gn/T/ipykernel_54699/1416090827.py:4: RuntimeWarning: Converting a CFTimeIndex with dates from a non-standard calendar, 'noleap', to a pandas.DatetimeIndex, which uses dates from the standard calendar.  This may lead to subtle errors in operations that depend on the length of time between dates.
  sr.index = sr.index.to_datetimeindex()

In [8]:
ams.to_csv('ams_pr.csv')

## using climextremes to calculate extreme value

In [7]:
# get annual max series (ams)

ams = df.groupby([df.time.dt.year])['pr'].max()
ams = ams.reset_index()
ams

     time        pr
0    1850  0.006327
1    1851  0.005336
2    1852  0.005973
3    1853  0.011385
4    1854  0.006396
..    ...       ...
151  2001  0.006570
152  2002  0.007323
153  2003  0.005163
154  2004  0.005696
155  2005  0.007891

[156 rows x 2 columns]

In [37]:
result = climext.fit_gev(np.array(ams.pr), returnPeriod = 10, returnValue = 0.011228, 
                         getFit = True, getParams = True, bootSE = True)

R[write to console]: Warning in log(z) :
R[write to console]:  NaNs produced

R[write to console]: Warning in log(z) :
R[write to console]:  NaNs produced

R[write to console]: Warning in (function (y, x = NULL, locationFun = NULL, scaleFun = NULL,  :
R[write to console]:

R[write to console]:  fit_gev: optimization failed; see 'info' in returned object. You may want to run 'fit_gev()' with argument 'getFit = TRUE' to see more details regarding the attempted optimization. You may also want to try a different optimization method or increase the maximum number of iterations.

In [38]:
result

{'info': {'convergence': array([0], dtype=int32),
  'counts_names': array(['function', 'gradient'], dtype='<U8'),
  'counts': array([82., nan]),
  'message': array(['fitting produced missing or invalid estimates or standard errors'],
        dtype='<U64'),
  'failure': array([1], dtype=int32)},
 'fit': {'call': Rlang( fevd(x = .y ~ 1, data = x, location.fun = locationFun, scale.fun = scaleFun,  ),
  'data.name': array(['.y ~ 1', 'x'], dtype='<U6'),
  'weights': array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1.]),
  'in.data': array([1], dtype=int32),
  'x.fun': None,
  'missing.values_names': array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12',
         '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23',
         '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34',
         '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45',
         '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56',
         '57', '58', '59', '60', '61', '62', '63', '64', '65', '66', '67',
         '68', '69', '70', '71', '72', '73', '74', '75', '76', '77', '78',
         '79', '80', '81', '82', '83', '84', '85', '86', '87', '88', '89',
         '90', '91', '92', '93', '94', '95', '96', '97', '98', '99', '100',
         '101', '102', '103', '104', '105', '106', '107', '108', '109',
         '110', '111', '112', '113', '114', '115', '116', '117', '118',
         '119', '120', '121', '122', '123', '124', '125', '126', '127',
         '128', '129', '130', '131', '132', '133', '134', '135', '136',
         '137', '138', '139', '140', '141', '142', '143', '144', '145',
         '146', '147', '148', '149', '150', '151', '152', '153', '154',
         '155', '156'], dtype='<U3'),
  'missing.values': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0], dtype=int32),
  'x': array([0.00632722, 0.00533573, 0.00597291, 0.01138519, 0.00639578,
         0.00719352, 0.00458417, 0.00440954, 0.00605171, 0.00482239,
         0.00478347, 0.00628513, 0.00686056, 0.00630192, 0.00555687,
         0.00755327, 0.00706636, 0.00772885, 0.0056999 , 0.00501369,
         0.00754593, 0.00661957, 0.00571094, 0.00504686, 0.00612184,
         0.00660656, 0.00287256, 0.00710592, 0.00680195, 0.00515655,
         0.00865688, 0.00510846, 0.00680174, 0.00636516, 0.00861473,
         0.00632117, 0.00445915, 0.00881307, 0.00460929, 0.00614788,
         0.00679942, 0.00658641, 0.00415065, 0.00499852, 0.00433857,
         0.00572467, 0.00658081, 0.0068381 , 0.00548156, 0.01122841,
         0.00516568, 0.00267339, 0.00380618, 0.00561129, 0.00642634,
         0.0034878 , 0.00902922, 0.00640744, 0.00742546, 0.00836618,
         0.00689205, 0.00499612, 0.00657691, 0.00442853, 0.0070892 ,
         0.00644677, 0.00438437, 0.00479395, 0.00622742, 0.00538048,
         0.00666658, 0.0099411 , 0.00609499, 0.00639306, 0.00542899,
         0.00514707, 0.00961465, 0.00409495, 0.00340886, 0.00351197,
         0.00542304, 0.00676767, 0.0052394 , 0.00711911, 0.00613477,
         0.00556943, 0.00330958, 0.00478979, 0.006902  , 0.00578217,
         0.00533116, 0.00515178, 0.00676711, 0.0065627 , 0.00714146,
         0.00617309, 0.00501318, 0.00923235, 0.00408742, 0.00471999,
         0.00667916, 0.00615193, 0.00595244, 0.00543113, 0.00452494,
         0.00357762, 0.00743257, 0.00596676, 0.00899108, 0.00495935,
         0.00448802, 0.00495412, 0.00477085, 0.00694767, 0.00547517,
         0.00645743, 0.00719479, 0.00481807, 0.00506824, 0.00487724,
         0.00705636, 0.0070618 , 0.00713457, 0.004483  , 0.0098784 ,
         0.00630022, 0.0046245 , 0.00616329, 0.00441546, 0.00630242,
         0.00334647, 0.00647531, 0.01013071, 0.00392299, 0.00687373,
         0.00834656, 0.0048666 , 0.00596596, 0.01034067, 0.0033691 ,
         0.00606727, 0.00572863, 0.00685388, 0.01000136, 0.00291528,
         0.0042572 , 0.00598564, 0.00471607, 0.00559395, 0.00746427,
         0.00422097, 0.00656966, 0.00732296, 0.00516276, 0.00569578,
         0.00789138]),
  'cov.data': rec.array([(0.00632722,), (0.00533573,), (0.00597291,), (0.01138519,),
             (0.00639578,), (0.00719352,), (0.00458417,), (0.00440954,),
             (0.00605171,), (0.00482239,), (0.00478347,), (0.00628513,),
             (0.00686056,), (0.00630192,), (0.00555687,), (0.00755327,),
             (0.00706636,), (0.00772885,), (0.0056999 ,), (0.00501369,),
             (0.00754593,), (0.00661957,), (0.00571094,), (0.00504686,),
             (0.00612184,), (0.00660656,), (0.00287256,), (0.00710592,),
             (0.00680195,), (0.00515655,), (0.00865688,), (0.00510846,),
             (0.00680174,), (0.00636516,), (0.00861473,), (0.00632117,),
             (0.00445915,), (0.00881307,), (0.00460929,), (0.00614788,),
             (0.00679942,), (0.00658641,), (0.00415065,), (0.00499852,),
             (0.00433857,), (0.00572467,), (0.00658081,), (0.0068381 ,),
             (0.00548156,), (0.01122841,), (0.00516568,), (0.00267339,),
             (0.00380618,), (0.00561129,), (0.00642634,), (0.0034878 ,),
             (0.00902922,), (0.00640744,), (0.00742546,), (0.00836618,),
             (0.00689205,), (0.00499612,), (0.00657691,), (0.00442853,),
             (0.0070892 ,), (0.00644677,), (0.00438437,), (0.00479395,),
             (0.00622742,), (0.00538048,), (0.00666658,), (0.0099411 ,),
             (0.00609499,), (0.00639306,), (0.00542899,), (0.00514707,),
             (0.00961465,), (0.00409495,), (0.00340886,), (0.00351197,),
             (0.00542304,), (0.00676767,), (0.0052394 ,), (0.00711911,),
             (0.00613477,), (0.00556943,), (0.00330958,), (0.00478979,),
             (0.006902  ,), (0.00578217,), (0.00533116,), (0.00515178,),
             (0.00676711,), (0.0065627 ,), (0.00714146,), (0.00617309,),
             (0.00501318,), (0.00923235,), (0.00408742,), (0.00471999,),
             (0.00667916,), (0.00615193,), (0.00595244,), (0.00543113,),
             (0.00452494,), (0.00357762,), (0.00743257,), (0.00596676,),
             (0.00899108,), (0.00495935,), (0.00448802,), (0.00495412,),
             (0.00477085,), (0.00694767,), (0.00547517,), (0.00645743,),
             (0.00719479,), (0.00481807,), (0.00506824,), (0.00487724,),
             (0.00705636,), (0.0070618 ,), (0.00713457,), (0.004483  ,),
             (0.0098784 ,), (0.00630022,), (0.0046245 ,), (0.00616329,),
             (0.00441546,), (0.00630242,), (0.00334647,), (0.00647531,),
             (0.01013071,), (0.00392299,), (0.00687373,), (0.00834656,),
             (0.0048666 ,), (0.00596596,), (0.01034067,), (0.0033691 ,),
             (0.00606727,), (0.00572863,), (0.00685388,), (0.01000136,),
             (0.00291528,), (0.0042572 ,), (0.00598564,), (0.00471607,),
             (0.00559395,), (0.00746427,), (0.00422097,), (0.00656966,),
             (0.00732296,), (0.00516276,), (0.00569578,), (0.00789138,)],
            dtype=[('.y', '<f8')]),
  'method': array(['MLE'], dtype='<U3'),
  'type': array(['GEV'], dtype='<U3'),
  'period.basis': array(['year'], dtype='<U4'),
  'optim.args': {'method': array(['Nelder-Mead'], dtype='<U11')},
  'par.models': {'threshold': None,
   'location': None,
   'scale': None,
   'log.scale': array([0], dtype=int32),
   'shape': None,
   'term.names': {'threshold': array([], dtype=float64),
    'location': array([], dtype=float64),
    'scale': array([], dtype=float64),
    'shape': array([], dtype=float64)}},
  'const.loc': array([1], dtype=int32),
  'const.scale': array([1], dtype=int32),
  'const.shape': array([1], dtype=int32),
  'n': array([156], dtype=int32),
  'na.action': array(['na.fail'], dtype='<U7'),
  'parnames': array(['location', 'scale', 'shape'], dtype='<U8'),
  'results': {'par_names': array(['location', 'scale', 'shape'], dtype='<U8'),
   'par': array([ 0.00536516,  0.00143518, -0.10129427]),
   'value': array([-784.72469261]),
   'counts_names': array(['function', 'gradient'], dtype='<U8'),
   'counts': array([82., nan]),
   'convergence': array([0], dtype=int32),
   'message': None,
   'hessian_row_names': array(['location', 'scale', 'shape'], dtype='<U8'),
   'hessian_column_names': array(['location', 'scale', 'shape'], dtype='<U8'),
   'hessian': array([[7.41930864e+07,            nan, 6.96577559e+04],
          [           nan,            nan,            nan],
          [6.96577559e+04,            nan, 5.12811327e+02]]),
   'num.pars': {'location': array([1], dtype=int32),
    'scale': array([1], dtype=int32),
    'shape': array([1], dtype=int32)}},
  'initial.results': {'Lmoments': {'pars_names': array(['location', 'scale', 'shape'], dtype='<U8'),
    'pars': array([ 0.00536993,  0.00142337, -0.10451591]),
    'likelihood': array([-784.7075936])},
   'MOM': {'pars_names': array(['location', 'scale', 'shape'], dtype='<U8'),
    'pars': array([5.31566243e-03, 1.00000000e-08, 1.00000000e-08]),
    'likelihood': array([inf])}}}}